# Generated by Django 5.2.4 on 2025-07-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
