version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: watan-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: watan
    ports:
      - '5432:5432'
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: watan-redis-dev
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    # Optional: run backend inside compose for consistent network
    build: ./backend
    container_name: watan-backend-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/watan
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: local-dev-secret
      PUBLIC_TENANT_BASE_DOMAIN: localhost
      AUTO_MIGRATIONS: 'true'
      HOST: 0.0.0.0
      PORT: 3000
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./backend:/app
      - backend_node_modules_dev:/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pg_data_dev:
  backend_node_modules_dev:
