import psycopg
conn = psycopg.connect('host=localhost port=5432 dbname=watan user=postgres password=Asdf1212asdf.')
cursor = conn.cursor()
cursor.execute('UPDATE integrations SET debt = 1200.00, "debtUpdatedAt" = NOW() WHERE provider = \'znet\'')
conn.commit()
print('✅ تم تحديث الدين إلى 1200.00 ليرة')
cursor.execute('SELECT name, balance, debt, balance - debt as net FROM integrations WHERE provider = \'znet\'')
result = cursor.fetchone()
print(f'📊 الاسم: {result[0]}')
print(f'   الرصيد: {result[1]}')
print(f'   الدين: {result[2]}')
print(f'   المحصلة: {result[3]}')
conn.close()
