# Generated by Django 5.0.7 on 2025-10-17 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='عنوان الإعلان', max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(help_text='محتوى الإعلان (يدعم HTML)', verbose_name='المحتوى')),
                ('announcement_type', models.CharField(choices=[('info', 'معلومة'), ('success', 'نجاح'), ('warning', 'تحذير'), ('update', 'تحديث'), ('announcement', 'إعلان')], default='info', max_length=20, verbose_name='نوع الإعلان')),
                ('icon', models.CharField(blank=True, help_text='اسم الأيقونة (مثل: bell, info-circle, check-circle)', max_length=50, null=True, verbose_name='الأيقونة')),
                ('order', models.IntegerField(default=0, help_text='ترتيب العرض (الأصغر يظهر أولاً)', verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, help_text='هل الإعلان نشط ومرئي؟', verbose_name='نشط')),
                ('is_global', models.BooleanField(default=True, help_text='إذا كان نعم: يظهر لجميع المستأجرين. إذا كان لا: خاص بمستأجر محدد', verbose_name='عام')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='إذا كان الإعلان خاص بمستأجر معين (اتركه فارغاً للإعلانات العامة)', null=True, verbose_name='معرف المستأجر')),
                ('start_date', models.DateTimeField(blank=True, help_text='تاريخ بدء عرض الإعلان (اختياري)', null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(blank=True, help_text='تاريخ انتهاء عرض الإعلان (اختياري)', null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'db_table': 'dj_dashboard_announcements',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'is_global'], name='dj_dashboar_is_acti_ca68d0_idx'), models.Index(fields=['tenant_id', 'is_active'], name='dj_dashboar_tenant__d4af26_idx'), models.Index(fields=['order'], name='dj_dashboar_order_adb526_idx')],
            },
        ),
    ]
