# Generated by Django 5.0.7 on 2025-10-17 02:36

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='حجم مناسب: 1200x400 بكسل', upload_to='banners/', verbose_name='الصورة')),
                ('tenant_id', models.UUIDField(blank=True, help_text='إذا كان فارغاً، سيظهر لجميع المستأجرين', null=True, verbose_name='معرف المستأجر')),
                ('order', models.IntegerField(default=0, help_text='من 0 إلى 2 (الحد الأقصى 3 صور)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('link', models.URLField(blank=True, help_text='رابط اختياري عند النقر على الصورة', null=True, verbose_name='الرابط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'صورة سلايدر',
                'verbose_name_plural': 'صور السلايدر',
                'db_table': 'dj_banners',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='dj_banners_tenant__1ebce5_idx'), models.Index(fields=['order'], name='dj_banners_order_a5a26f_idx')],
            },
        ),
    ]
