# Generated by Django 5.0.7 on 2025-10-17 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_capital_adjustments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='capitaladjustment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
