from django.urls import path
from .views import (
    ProductsListView,
    ProductDetailView,
    UserProductDetailView,
    PriceGroupsListCreateView,
    PriceGroupDetailView,
    UsersPriceGroupsView,
    GlobalProductsListView,
    CloneGlobalToTenantView,
    SyncFromGlobalView,
    ProductBridgesView,
    ProductPackagesCreateView,
    PackageBasicUpdateView,
    PackageCodeUpdateView,
    PackageUnitUpdateView,
    PackageDeleteView,
    AdminProductSupportsCounterView,
    PackagePricesFetchView,
    PackagePricesUpdateView,
)

urlpatterns = [
    path('', ProductsListView.as_view(), name='products-list'),
    path('user/<uuid:id>', UserProductDetailView.as_view(), name='products-user-detail'),
    path('user/<uuid:id>/', UserProductDetailView.as_view(), name='products-user-detail-slash'),
    path('<uuid:id>', ProductDetailView.as_view(), name='products-detail'),
    path('<uuid:id>/bridges', ProductBridgesView.as_view(), name='products-bridges'),
    path('<uuid:id>/bridges/', ProductBridgesView.as_view(), name='products-bridges-slash'),
    path('<str:id>/bridges', ProductBridgesView.as_view(), name='products-bridges-str'),
    path('<str:id>/bridges/', ProductBridgesView.as_view(), name='products-bridges-str-slash'),
    # packages CRUD (tenant-scoped)
    path('<uuid:id>/packages', ProductPackagesCreateView.as_view(), name='product-packages-create'),
    path('<uuid:id>/packages/', ProductPackagesCreateView.as_view(), name='product-packages-create-slash'),
    path('packages/<uuid:pkg_id>/basic', PackageBasicUpdateView.as_view(), name='product-package-basic'),
    path('packages/<uuid:pkg_id>/basic/', PackageBasicUpdateView.as_view(), name='product-package-basic-slash'),
    path('packages/<uuid:pkg_id>/code', PackageCodeUpdateView.as_view(), name='product-package-code'),
    path('packages/<uuid:pkg_id>/code/', PackageCodeUpdateView.as_view(), name='product-package-code-slash'),
    path('packages/<uuid:pkg_id>/unit', PackageUnitUpdateView.as_view(), name='product-package-unit'),
    path('packages/<uuid:pkg_id>/unit/', PackageUnitUpdateView.as_view(), name='product-package-unit-slash'),
    path('packages/<uuid:pkg_id>/', PackageDeleteView.as_view(), name='product-package-delete'),
    path('packages/prices', PackagePricesFetchView.as_view(), name='product-packages-prices'),
    path('packages/prices/', PackagePricesFetchView.as_view(), name='product-packages-prices-slash'),
    path('packages/<uuid:pkg_id>/prices', PackagePricesUpdateView.as_view(), name='product-package-prices'),
    path('packages/<uuid:pkg_id>/prices/', PackagePricesUpdateView.as_view(), name='product-package-prices-slash'),
    path('packages/<str:pkg_id>/prices', PackagePricesUpdateView.as_view(), name='product-package-prices-str'),
    path('packages/<str:pkg_id>/prices/', PackagePricesUpdateView.as_view(), name='product-package-prices-str-slash'),
    path('<uuid:id>/clone-to-tenant', CloneGlobalToTenantView.as_view(), name='products-clone-to-tenant'),
    path('<uuid:id>/clone-to-tenant/', CloneGlobalToTenantView.as_view(), name='products-clone-to-tenant-slash'),
    path('<str:id>/clone-to-tenant', CloneGlobalToTenantView.as_view(), name='products-clone-to-tenant-str'),
    path('<str:id>/clone-to-tenant/', CloneGlobalToTenantView.as_view(), name='products-clone-to-tenant-str-slash'),
    path('<uuid:id>/sync-from-global', SyncFromGlobalView.as_view(), name='products-sync-from-global'),
    path('<uuid:id>/sync-from-global/', SyncFromGlobalView.as_view(), name='products-sync-from-global-slash'),
    path('<str:id>/sync-from-global', SyncFromGlobalView.as_view(), name='products-sync-from-global-str'),
    path('<str:id>/sync-from-global/', SyncFromGlobalView.as_view(), name='products-sync-from-global-str-slash'),
    path('global', GlobalProductsListView.as_view(), name='products-global'),
    path('global/', GlobalProductsListView.as_view(), name='products-global-slash'),
    # price groups
    path('price-groups', PriceGroupsListCreateView.as_view(), name='price-groups-list-create'),
    path('price-groups/<uuid:id>', PriceGroupDetailView.as_view(), name='price-groups-detail'),
    path('price-groups/users', UsersPriceGroupsView.as_view(), name='price-groups-users'),
]

admin_urlpatterns = [
    path('products/<uuid:id>/supports-counter', AdminProductSupportsCounterView.as_view(), name='admin-products-supports-counter'),
    path('products/<uuid:id>/supports-counter/', AdminProductSupportsCounterView.as_view(), name='admin-products-supports-counter-slash'),
    path('products/<str:id>/supports-counter', AdminProductSupportsCounterView.as_view(), name='admin-products-supports-counter-str'),
    path('products/<str:id>/supports-counter/', AdminProductSupportsCounterView.as_view(), name='admin-products-supports-counter-str-slash'),
]
