# Generated by Django 5.2.4 on 2025-07-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_packageprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpackage',
            name='price',
        ),
        migrations.AddField(
            model_name='productpackage',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
