# Generated by Django 5.0.7 on 2025-09-25 15:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('tenant_id', models.UUIDField(db_column='tenantId')),
                        ('type', models.CharField(db_column='type', default='announcement', max_length=40)),
                        ('title', models.CharField(blank=True, db_column='title', max_length=200, null=True)),
                        ('message', models.TextField(db_column='message')),
                        ('meta', models.JSONField(blank=True, db_column='meta', null=True)),
                        ('is_read', models.BooleanField(db_column='isRead', default=False)),
                        ('read_at', models.DateTimeField(blank=True, db_column='readAt', null=True)),
                        ('link', models.CharField(blank=True, db_column='link', max_length=300, null=True)),
                        ('channel', models.CharField(db_column='channel', default='in_app', max_length=20)),
                        ('priority', models.CharField(db_column='priority', default='normal', max_length=10)),
                        ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                        (
                            'user',
                            models.ForeignKey(
                                db_column='user_id',
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name='notifications',
                                to='users.legacyuser',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'notifications',
                        'ordering': ['-created_at', '-id'],
                        'managed': False,
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
