# Generated by Django 5.0.7 on 2025-09-25 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePrice',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_column='tenantId', db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'سعر الباقة',
                'verbose_name_plural': 'أسعار الباقات',
                'db_table': 'package_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_column='tenantId', db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
            ],
            options={
                'verbose_name': 'مجموعة أسعار',
                'verbose_name_plural': 'مجموعات الأسعار',
                'db_table': 'price_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_column='tenantId', db_index=True)),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_image_url', models.CharField(blank=True, db_column='customImageUrl', max_length=500, null=True)),
                ('custom_alt_text', models.CharField(blank=True, db_column='customAltText', max_length=300, null=True)),
                ('thumb_small_url', models.CharField(blank=True, db_column='thumbSmallUrl', max_length=500, null=True)),
                ('thumb_medium_url', models.CharField(blank=True, db_column='thumbMediumUrl', max_length=500, null=True)),
                ('thumb_large_url', models.CharField(blank=True, db_column='thumbLargeUrl', max_length=500, null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True, verbose_name='الحالة')),
                ('supports_counter', models.BooleanField(db_column='supportsCounter', default=False)),
                ('source_global_product_id', models.UUIDField(blank=True, db_column='sourceGlobalProductId', null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_column='tenantId', db_index=True)),
                ('public_code', models.IntegerField(blank=True, db_column='publicCode', null=True, verbose_name='رقم الربط (public code)')),
                ('name', models.CharField(max_length=160, null=True, verbose_name='اسم الباقة')),
                ('description', models.TextField(null=True)),
                ('image_url', models.CharField(db_column='imageUrl', max_length=500, null=True)),
                ('base_price', models.DecimalField(db_column='basePrice', decimal_places=2, default=0, max_digits=10)),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type', models.CharField(default='fixed', max_length=10)),
                ('unit_name', models.CharField(db_column='unitName', max_length=40, null=True)),
                ('unit_code', models.CharField(db_column='unitCode', max_length=40, null=True)),
                ('min_units', models.IntegerField(db_column='minUnits', null=True)),
                ('max_units', models.IntegerField(db_column='maxUnits', null=True)),
                ('step', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('provider_name', models.CharField(db_column='providerName', max_length=120, null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True, verbose_name='الحالة')),
            ],
            options={
                'db_table': 'product_packages',
                'managed': False,
            },
        ),
    ]
