# Generated by Django 5.0.7 on 2025-10-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productpackage',
            options={'managed': False, 'verbose_name': 'باقة منتج', 'verbose_name_plural': 'باقات المنتجات'},
        ),
    ]
