# Generated by Django 5.0.7 on 2025-09-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_legacyuser_user_force_totp_enroll_and_more'),
    ]

    operations = []
