# Generated by Django 5.0.7 on 2025-10-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_legacypasswordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legacyuser',
            options={'managed': False, 'verbose_name': 'Legacy User (Old NestJS Backend)', 'verbose_name_plural': 'Legacy Users (Old NestJS Backend - REFERENCE ONLY)'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
    ]
