# Generated by ChatGPT on 2025-10-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_create_missing_totp_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant_id',
            field=models.UUIDField(blank=True, null=True, db_index=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='price_group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_currency_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='legacy_password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
