# Generated by Django 5.0.7 on 2025-10-15 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_client_api_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('debit', 'خصم'), ('credit', 'إضافة'), ('refund', 'استرجاع'), ('adjustment', 'تعديل يدوي')], max_length=20, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='المبلغ')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='العملة')),
                ('balance_before', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='الرصيد قبل')),
                ('balance_after', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='الرصيد بعد')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('order_id', models.UUIDField(blank=True, null=True, verbose_name='رقم الطلب')),
                ('payment_id', models.UUIDField(blank=True, null=True, verbose_name='رقم عملية الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='معلومات إضافية')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'معاملة محفظة',
                'verbose_name_plural': 'معاملات المحفظة',
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallet_tran_user_id_1da2e3_idx'), models.Index(fields=['transaction_type'], name='wallet_tran_transac_377ecc_idx'), models.Index(fields=['order_id'], name='wallet_tran_order_i_f9d811_idx')],
            },
        ),
    ]
