# Generated by Django 5.0.7 on 2025-10-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_wallet_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('approved', 'قبول طلب'), ('rejected', 'رفض طلب'), ('status_change', 'تغيير الحالة'), ('deposit', 'شحن المحفظة')], max_length=20, verbose_name='نوع العملية'),
        ),
    ]
