# Generated by Django 5.0.7 on 2025-10-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_update_transaction_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان الكامل'),
        ),
        migrations.AddField(
            model_name='user',
            name='documents',
            field=models.JSONField(blank=True, default=list, help_text='حد أقصى 3 صور - يتم تخزين روابط الصور', null=True, verbose_name='الوثائق'),
        ),
    ]
