# Generated by Django 5.0.7 on 2025-09-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'مستأجر', 'verbose_name_plural': 'المستأجرون'},
        ),
    ]
