name: Remote diagnostics

on:
  workflow_dispatch:

jobs:
  diagnostics:
    name: Remote diagnostics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Preflight (print compose config)
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" '
            set -e
            cd /root/watan
            docker-compose --version || true
            docker-compose config | sed -n "1,120p" || true
          '

      - name: Docker status + envs
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" '
            set -e
            cd /root/watan
            docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" || true
            echo "=== /root/watan/.env ==="; sed -n "1,80p" .env || true
            echo "=== backend env ==="
            docker exec watan-backend /bin/sh -c "printenv | grep -E '^(DATABASE_URL|REDIS_URL|JWT_SECRET|NODE_ENV)=' || true" || true
            echo "=== backend logs (tail) ==="
            docker-compose logs --tail=80 backend || true
          '

      - name: PG connectivity from host
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" '
            ss -ltnp | grep ":5432" || true
          '
