name: Security Baseline

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'

jobs:
  deps-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Backend audit
        working-directory: backend
        run: |
          npm ci --no-audit --no-fund
          npm audit --production || true
      - name: Frontend audit
        working-directory: frontend
        run: |
          npm ci --no-audit --no-fund
          npm audit --production || true

  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: auto
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          args: detect --redact --no-git -s . || true

  trivy-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t watan-${{ matrix.component }}:ci ./ ${{ matrix.component }}
      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'watan-${{ matrix.component }}:ci'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

  zap-baseline:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: OWASP ZAP Baseline (staging)
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://staging.wtn4.com'
          rules_file_name: '.zap-rules'
          cmd_options: '-a'

  aggregate:
    runs-on: ubuntu-latest
    needs: [deps-audit, semgrep, gitleaks, trivy-images]
    steps:
      - name: Summary
        run: |
          echo 'Security baseline jobs finished. Review individual job logs.'
